stages:
  - build
  - test
  - publish

before_script:
  - chmod +x gradlew

build:
  stage: build
  tags:
    - java
    - gradle
  script:
    - ./gradlew build publishToMavenLocal


publish:
  stage: publish
  tags:
    - java
    - gradle
  script:
    - ./gradlew generatePomFileForMavenJavaPublication publish
  only:
    - tags
