stages:
  - build
  - test
  - publish

before_script:
  - chmod +x gradlew

build:
  stage: build
  tags:
    - java
    - gradle
  script:
    - cd plugin
    - ../gradlew build publishToMavenLocal
    - cd ..
    - ./gradlew build

unit-test:
  stage: test
  tags:
    - java
    - gradle
  script:
    - ./gradlew test

integration:
  stage: test
  tags:
    - java
    - gradle
    - terraform
  script:
    - ./gradlew terraform -P conf_aws_access_key=$AWS_ACCESS_KEY -P conf_aws_secret_key=$AWS_SECRET_KEY

publish:
  stage: publish
  tags:
    - java
    - gradle
  script:
    - gradle generatePomFileForMavenJavaPublication publish
  only:
    - tags
