stages:
  - build
  - test
  - publish

before_script:
  - chmod +x gradlew

build:
  stage: build
  tags:
    - java
    - gradle
  script:
    ./gradlew build publishToMavenLocal

unit-test:
  stage: test
  tags:
    - java
    - gradle
  script:
    - ./gradlew test

integration:
  stage: test
  tags:
    - java
    - gradle
    - terraform
  script:
    - ./gradlew --refresh-dependencies terraform -P tfAwsAccessKey="$AWS_ACCESS_KEY" -P tfAwsSecretKey="$AWS_SECRET_KEY"

publish:
  stage: publish
  tags:
    - java
    - gradle
  script:
    - gradle generatePomFileForMavenJavaPublication publish
  only:
    - tags
