stages:
  - build
  - test
  - publish

before_script:
  - chmod +x gradlew

build:
  stage: build
  tags:
    - java
    - gradle
  script:
    - cd plugin
    - ../gradlew build publishToMavenLocal

unit-test:
  stage: test
  tags:
    - java
    - gradle
  script:
    - cd plugin
    - ../gradlew test
    -  cd ../testProject
    - ../gradlew test

integration:
  stage: test
  tags:
    - java
    - gradle
    - terraform
  script:
    - cd plugin
    - ../gradlew build
    - cd ..
    - ./gradlew --refresh-dependencies terraform -P tfAwsAccessKey="$AWS_ACCESS_KEY" -P tfAwsSecretKey="$AWS_SECRET_KEY"

publish:
  stage: publish
  tags:
    - java
    - gradle
  script:
    - cd plugin
    - gradle generatePomFileForMavenJavaPublication publish
  only:
    - tags
